/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        // CharacterCreation classUnderTest = new CharacterCreation();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
